import type { Tour } from "./types";

// Datos del catálogo PDF de Saira (junio 2024).
// Los `comparablePlatformPriceBRL` son estimaciones (~1.42× del directo,
// equivalente a una comisión de plataforma de ~30%). Validar con Saraí.
// Las imágenes son placeholders SVG por ahora; David entrega definitivas.

const placeholderHero = (slug: string) =>
  `/saira/tours/${slug}/hero.jpg`;

export const tours: Tour[] = [
  // ───────────────────────────────  Ecotour / Trilhas
  {
    slug: "cerro-dois-irmaos",
    name: "Cerro Dois Irmãos",
    category: "ecotour",
    difficulty: "facil-moderada",
    durationMinutes: 45,
    priceBRL: 160,
    comparablePlatformPriceBRL: 230,
    hasSunriseOption: true,
    priceSunriseBRL: 180,
    images: [placeholderHero("cerro-dois-irmaos")],
    heroImage: placeholderHero("cerro-dois-irmaos"),
    minPeople: 1,
    maxPeople: 8,
  },
  {
    slug: "pedra-da-gavea",
    name: "Pedra da Gávea",
    category: "ecotour",
    difficulty: "dificil",
    durationMinutes: 180, // 2.5–3.5h promedio 3h
    priceBRL: 190,
    comparablePlatformPriceBRL: 270,
    images: [placeholderHero("pedra-da-gavea")],
    heroImage: placeholderHero("pedra-da-gavea"),
    minPeople: 2,
    maxPeople: 6,
  },
  {
    slug: "garganta-do-ceu",
    name: "Garganta do Céu",
    category: "ecotour",
    difficulty: "moderada-dificil",
    durationMinutes: 105, // 1.5–2h promedio
    priceBRL: 170,
    comparablePlatformPriceBRL: 240,
    images: [placeholderHero("garganta-do-ceu")],
    heroImage: placeholderHero("garganta-do-ceu"),
    minPeople: 1,
    maxPeople: 8,
  },
  {
    slug: "trilha-corcovado",
    name: "Trilha Corcovado",
    category: "ecotour",
    difficulty: "moderada",
    durationMinutes: 150, // 2–3h promedio
    priceBRL: 250,
    comparablePlatformPriceBRL: 355,
    images: [placeholderHero("trilha-corcovado")],
    heroImage: placeholderHero("trilha-corcovado"),
    minPeople: 1,
    maxPeople: 8,
  },
  {
    slug: "cerro-urca-pao-de-acucar",
    name: "Cerro de Urca · Pão de Açúcar",
    category: "ecotour",
    difficulty: "facil",
    durationMinutes: 25, // 20–30min
    priceBRL: 0,
    priceOnRequest: true,
    images: [placeholderHero("cerro-urca-pao-de-acucar")],
    heroImage: placeholderHero("cerro-urca-pao-de-acucar"),
    minPeople: 1,
    maxPeople: 10,
  },
  {
    slug: "pedra-bonita",
    name: "Pedra Bonita",
    category: "ecotour",
    difficulty: "facil",
    durationMinutes: 30, // 20–40min
    priceBRL: 160,
    comparablePlatformPriceBRL: 225,
    images: [placeholderHero("pedra-bonita")],
    heroImage: placeholderHero("pedra-bonita"),
    minPeople: 1,
    maxPeople: 10,
  },
  {
    slug: "cerro-da-babilonia",
    name: "Cerro da Babilônia",
    category: "ecotour",
    difficulty: "facil-moderada",
    durationMinutes: 90, // 1–2h
    priceBRL: 160,
    comparablePlatformPriceBRL: 225,
    images: [placeholderHero("cerro-da-babilonia")],
    heroImage: placeholderHero("cerro-da-babilonia"),
    minPeople: 1,
    maxPeople: 8,
  },
  {
    slug: "mirante-dona-marta",
    name: "Mirante Dona Marta",
    category: "ecotour",
    difficulty: "variable",
    durationMinutes: null,
    priceBRL: 230,
    comparablePlatformPriceBRL: 325,
    images: [placeholderHero("mirante-dona-marta")],
    heroImage: placeholderHero("mirante-dona-marta"),
    minPeople: 1,
    maxPeople: 8,
  },
  {
    slug: "bico-do-papagaio",
    name: "Bico do Papagaio",
    category: "ecotour",
    difficulty: "moderada-dificil",
    durationMinutes: 120,
    priceBRL: 190,
    comparablePlatformPriceBRL: 270,
    images: [placeholderHero("bico-do-papagaio")],
    heroImage: placeholderHero("bico-do-papagaio"),
    minPeople: 2,
    maxPeople: 6,
  },
  {
    slug: "floresta-tijuca-grutas",
    name: "Floresta da Tijuca · Circuito das Grutas",
    category: "ecotour",
    difficulty: "facil-moderada",
    durationMinutes: null,
    priceBRL: 180,
    comparablePlatformPriceBRL: 255,
    images: [placeholderHero("floresta-tijuca-grutas")],
    heroImage: placeholderHero("floresta-tijuca-grutas"),
    minPeople: 2,
    maxPeople: 10,
  },
  {
    slug: "floresta-tijuca-cascadas",
    name: "Floresta da Tijuca · Circuito das Cascadas",
    category: "ecotour",
    difficulty: "facil-moderada",
    durationMinutes: null,
    priceBRL: 180,
    comparablePlatformPriceBRL: 255,
    images: [placeholderHero("floresta-tijuca-cascadas")],
    heroImage: placeholderHero("floresta-tijuca-cascadas"),
    minPeople: 2,
    maxPeople: 10,
  },
  {
    slug: "pico-da-tijuca",
    name: "Pico da Tijuca",
    category: "ecotour",
    difficulty: "moderada-dificil",
    durationMinutes: 120,
    priceBRL: 190,
    comparablePlatformPriceBRL: 270,
    images: [placeholderHero("pico-da-tijuca")],
    heroImage: placeholderHero("pico-da-tijuca"),
    minPeople: 1,
    maxPeople: 8,
  },

  // ───────────────────────────────  Aventura
  {
    slug: "parapente",
    name: "Parapente · Asa-Delta",
    category: "aventura",
    difficulty: "variable",
    durationMinutes: null,
    priceBRL: 900,
    comparablePlatformPriceBRL: 1280,
    images: [placeholderHero("parapente")],
    heroImage: placeholderHero("parapente"),
    minPeople: 1,
    maxPeople: 1,
  },
  {
    slug: "rapel",
    name: "Rapel",
    category: "aventura",
    difficulty: "variable",
    durationMinutes: null,
    priceBRL: 250,
    priceFromOnly: true,
    comparablePlatformPriceBRL: 355,
    images: [placeholderHero("rapel")],
    heroImage: placeholderHero("rapel"),
    minPeople: 1,
    maxPeople: 4,
  },
  {
    slug: "escalada",
    name: "Escalada",
    category: "aventura",
    difficulty: "variable",
    durationMinutes: null,
    priceBRL: 400,
    priceFromOnly: true,
    comparablePlatformPriceBRL: 570,
    images: [placeholderHero("escalada")],
    heroImage: placeholderHero("escalada"),
    minPeople: 1,
    maxPeople: 4,
  },
  {
    slug: "stand-up-paddle-amanecer",
    name: "Stand Up Paddle · Amanhecer",
    category: "aventura",
    difficulty: "facil",
    durationMinutes: null,
    priceBRL: 180,
    priceFromOnly: true,
    comparablePlatformPriceBRL: 255,
    images: [placeholderHero("stand-up-paddle-amanecer")],
    heroImage: placeholderHero("stand-up-paddle-amanecer"),
    minPeople: 1,
    maxPeople: 6,
  },
];

export function getTour(slug: string): Tour | undefined {
  return tours.find((t) => t.slug === slug);
}

export const tourSlugs = tours.map((t) => t.slug);
